import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import ClientOnly from '@/components/ClientOnly'
import { avenir, cerebri } from './fonts/fonts'

const poppins = Poppins({ 
  weight: ['100', '200','300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: {
    template: 'Poccash | %s',
    default: 'Poccash'
  },
  description: 'Generated by create Mr.Meng',
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${avenir.variable} ${cerebri.variable} scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-gray-100`}>
        <ClientOnly>
          {children}
        </ClientOnly>
      </body>
    </html>
  )
}
